var searchData=
[
  ['magic_20api_20methods_0',['Removed undocumented magic API methods',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2upgrading.html#autotoc_md595',1,'']]],
  ['mail_20addresses_1',['Obfuscating E-mail Addresses',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2appendixes_2tips.html#autotoc_md206',1,'']]],
  ['mailto_2',['Mailto',['../class_smarty_1_1_function_handler_1_1_mailto.html',1,'Smarty::FunctionHandler']]],
  ['mailto_3',['{mailto}',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2designers_2language-custom-functions_2language-function-mailto.html',1,'']]],
  ['math_4',['Math',['../class_smarty_1_1_function_handler_1_1_math.html',1,'Smarty::FunctionHandler']]],
  ['math_5',['{math}',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2designers_2language-custom-functions_2language-function-math.html',1,'']]],
  ['mbstring_6',['Mbstring',['../class_symfony_1_1_polyfill_1_1_mbstring_1_1_mbstring.html',1,'Symfony::Polyfill::Mbstring']]],
  ['me_7',['Is Smarty Right for Me?',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2features.html#autotoc_md520',1,'']]],
  ['merge_20compiled_20includes_8',['$merge_compiled_includes {variable.merge.compiled.includes}',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2programmers_2api-variables_2variable-merge-compiled-includes.html',1,'']]],
  ['methods_9',['methods',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2upgrading.html#autotoc_md594',1,'Removed Smarty API methods'],['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2upgrading.html#autotoc_md595',1,'Removed undocumented magic API methods']]],
  ['modified_20check_10',['$cache_modified_check {variable.cache.modified.check}',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2programmers_2api-variables_2variable-cache-modified-check.html',1,'']]],
  ['modifiercompiler_11',['ModifierCompiler',['../class_smarty_1_1_compile_1_1_modifier_compiler.html',1,'Smarty::Compile']]],
  ['modifiercompilerinterface_12',['ModifierCompilerInterface',['../interface_smarty_1_1_compile_1_1_modifier_1_1_modifier_compiler_interface.html',1,'Smarty::Compile::Modifier']]],
  ['modifiers_13',['Modifiers',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2designers_2language-combining-modifiers.html',1,'Combining Modifiers'],['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2designers_2language-modifiers_2index.html#autotoc_md352',1,'Combining Modifiers'],['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2designers_2language-modifiers_2index.html',1,'Variable Modifiers']]],
  ['modifiers_14',['modifiers',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2programmers_2api-variables_2variable-default-modifiers.html',1,'\\$default_modifiers {#variable.default.modifiers}'],['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2api_2extending_2modifiers.html',1,'Custom modifiers']]],
  ['modifiers_20in_20expressions_15',['Using modifiers in expressions',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2designers_2language-modifiers_2index.html#autotoc_md353',1,'']]],
  ['more_20embedded_20php_16',['No more embedded PHP',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2upgrading.html#autotoc_md602',1,'']]],
  ['motherctrl_17',['MotherCtrl',['../class_mother_ctrl.html',1,'']]],
  ['movieentity_18',['MovieEntity',['../class_movie_entity.html',1,'']]],
  ['multiple_20caches_20per_20template_19',['Multiple caches per template',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2api_2caching_2multiple-caches-per-template.html',1,'']]],
  ['mustcompile_20',['mustCompile',['../class_smarty_1_1_template.html#ac46605e0bc23758fe5854820ab1acfe5',1,'Smarty::Template']]],
  ['mute_20expected_20errors_21',['api-mute-expected-errors',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2programmers_2api-functions_2api-mute-expected-errors.html',1,'']]],
  ['muteundefinedornullwarnings_22',['muteUndefinedOrNullWarnings',['../class_smarty_1_1_smarty.html#a58c6a21e6826aa0cd6a614a3378a07f6',1,'Smarty::Smarty']]],
  ['muting_20php8_20warnings_23',['Muting PHP8 warnings',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2upgrading.html#autotoc_md599',1,'']]]
];
