var searchData=
[
  ['i_20have_20a_20question_0',['I Have a Question',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md120',1,'']]],
  ['i_20submit_20a_20good_20bug_20report_1',['How Do I Submit a Good Bug Report?',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md124',1,'']]],
  ['i_20submit_20a_20good_20enhancement_20suggestion_2',['How Do I Submit a Good Enhancement Suggestion?',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md127',1,'']]],
  ['i_20want_20to_20contribute_3',['I Want To Contribute',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md121',1,'']]],
  ['id_4',['id',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2programmers_2api-variables_2variable-cache-id.html',1,'\\$cache_id {#variable.cache.id}'],['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2programmers_2api-variables_2variable-compile-id.html',1,'\\$compile_id {#variable.compile.id}'],['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2programmers_2api-variables_2variable-smarty-debug-id.html',1,'\\$smarty_debug_id {#variable.smarty.debug.id}']]],
  ['if_20a_20template_20exists_5',['Testing if a template exists',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2api_2rendering.html#autotoc_md176',1,'']]],
  ['if_20a_20template_20is_20cached_6',['Checking if a template is cached',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2api_2caching_2basics.html#autotoc_md140',1,'']]],
  ['if_20elseif_20else_7',['{if},{elseif},{else}',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2designers_2language-builtin-functions_2language-function-if.html',1,'']]],
  ['important_8',['Why is separating PHP from templates important?',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2philosophy.html#autotoc_md543',1,'']]],
  ['improving_20the_20documentation_9',['Improving The Documentation',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md128',1,'']]],
  ['in_20child_20templates_20only_20_3a_10',['Option Flags (in child templates only):',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2designers_2language-builtin-functions_2language-function-block.html#autotoc_md242',1,'']]],
  ['in_20double_20quotes_11',['Embedding Vars in Double Quotes',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2designers_2language-basic-syntax_2language-syntax-quotes.html',1,'']]],
  ['in_20expressions_12',['Using modifiers in expressions',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2designers_2language-modifiers_2index.html#autotoc_md353',1,'']]],
  ['in_20functions_13',['Built-in Functions',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2designers_2language-builtin-functions_2index.html',1,'']]],
  ['in_20php_14',['Retrieving config variables in PHP',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2api_2variables_2config-files.html#autotoc_md191',1,'']]],
  ['in_20your_20templates_15',['Using native PHP-functions or userland functions in your templates',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2upgrading.html#autotoc_md589',1,'']]],
  ['in_5farray_16',['in_array',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2designers_2language-modifiers_2language-modifier-in__array.html',1,'']]],
  ['include_17',['{include}',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2designers_2language-builtin-functions_2language-function-include.html',1,'']]],
  ['includes_18',['$merge_compiled_includes {variable.merge.compiled.includes}',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2programmers_2api-variables_2variable-merge-compiled-includes.html',1,'']]],
  ['incompatible_20changes_20to_20custom_20plugins_19',['Backwards incompatible changes to custom plugins',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2upgrading.html#autotoc_md593',1,'']]],
  ['indent_20',['indent',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2designers_2language-modifiers_2language-modifier-indent.html',1,'']]],
  ['index_21',['.index',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2designers_2language-builtin-functions_2language-function-section.html#autotoc_md290',1,'']]],
  ['index_5fnext_22',['.index_next',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2designers_2language-builtin-functions_2language-function-section.html#autotoc_md292',1,'']]],
  ['index_5fprev_23',['.index_prev',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2designers_2language-builtin-functions_2language-function-section.html#autotoc_md291',1,'']]],
  ['indexes_24',['Array indexes',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2designers_2language-variables_2language-assigned-variables.html#autotoc_md492',1,'']]],
  ['inheritance_25',['Inheritance',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2api_2inheritance.html',1,'Template Inheritance'],['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2features.html#autotoc_md514',1,'Template Inheritance']]],
  ['inheritance_26',['Basic inheritance',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2api_2inheritance.html#autotoc_md170',1,'']]],
  ['install_27',['api-test-install',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2programmers_2api-functions_2api-test-install.html',1,'']]],
  ['installation_28',['Installation',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2api_2basics.html#autotoc_md132',1,'Installation'],['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2getting-started.html#autotoc_md528',1,'Installation'],['../dir_b5b87fd20f201bc4569a9d744b0ca740.html#autotoc_md607',1,'Installation']]],
  ['integration_29',['Integration',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2features.html#autotoc_md517',1,'']]],
  ['introduction_30',['Introduction',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2api_2caching_2multiple-caches-per-template.html#autotoc_md145',1,'']]],
  ['is_20cached_31',['is cached',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2programmers_2api-functions_2api-is-cached.html',1,'api-is-cached'],['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2api_2caching_2basics.html#autotoc_md140',1,'Checking if a template is cached']]],
  ['is_20not_32',['What Smarty is Not',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2features.html#autotoc_md519',1,'']]],
  ['is_20separating_20php_20from_20templates_20important_33',['Why is separating PHP from templates important?',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2philosophy.html#autotoc_md543',1,'']]],
  ['is_20smarty_34',['What is Smarty?',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2philosophy.html#autotoc_md540',1,'']]],
  ['is_20smarty_20right_20for_20me_35',['Is Smarty Right for Me?',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2features.html#autotoc_md520',1,'']]],
  ['is_5farray_36',['is_array',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2designers_2language-modifiers_2language-modifier-is__array.html',1,'']]],
  ['isset_37',['isset',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2designers_2language-modifiers_2language-modifier-isset.html',1,'']]],
  ['it_20work_38',['How does it work?',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2features.html#autotoc_md513',1,'']]],
  ['iteration_39',['.iteration',['../md__m_a_m_p_2htdocs_2_projet2_2vendor_2smarty_2smarty_2docs_2designers_2language-builtin-functions_2language-function-section.html#autotoc_md293',1,'']]]
];
